import Vapor

extension VersionResponse: Content {}
extension TagsResponse: Content {}
extension ShowRequest: Content {}
extension ShowResponse: Content {}
extension ChatRequest: Content {}
extension ChatResponse: Content {}
extension GenerateRequest: Content {}
extension GenerateResponse: Content {}
extension EmbedRequest: Content {}
extension EmbedResponse: Content {}
extension EmbeddingsRequest: Content {}
extension EmbeddingsResponse: Content {}
extension PullRequest: Content {}
extension PullResponse: Content {}
extension DeleteRequest: Content {}
extension CreateRequest: Content {}
extension WarmupRequest: Content {}
extension AbortRequest: Content {}
extension UnloadRequest: Content {}
extension PsResponse: Content {}
extension OpenAIChatRequest: Content {}
extension OpenAIChatResponse: Content {}
extension OpenAICompletionRequest: Content {}
extension OpenAICompletionResponse: Content {}
extension OpenAIModelList: Content {}
extension OpenAIEmbeddingRequest: Content {}
extension OpenAIEmbeddingResponse: Content {}
extension AnthropicMessagesRequest: Content {}
extension AnthropicMessagesResponse: Content {}
extension AnthropicTokenCountResponse: Content {}
